// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using MyDashDataAPI.Models;
using Newtonsoft.Json.Linq;

namespace MyDashDataAPI.Models
{
    public static partial class TodoCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<Todo> DeserializeJson(JToken inputObject)
        {
            IList<Todo> deserializedObject = new List<Todo>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                Todo todo = new Todo();
                todo.DeserializeJson(iListValue);
                deserializedObject.Add(todo);
            }
            return deserializedObject;
        }
    }
}
